name: Build MAIN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        nim: ["binary:1.6.18"]
    uses: ./.github/workflows/builder.yaml
    with:
      container: 'nimletter'
      release: 'main'
      nimversion: ${{ matrix.nim }}
    secrets: inherit