name: Build PROD

on:
  push:
    tags:
      - 'v*'

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        nim: ["binary:2.2.0"]
    uses: ./.github/workflows/builder.yaml
    with:
      container: 'nimletter'
      release: 'prod'
      nimversion: ${{ matrix.nim }}
    secrets: inherit
